variable "name" {}
variable "region" {}
variable "tags" {}

variable "rds_engine" {}
variable "rds_engine_version" {}
variable "rds_instance_class" {}
variable "rds_allocated_storage" {}
variable "rds_max_allocated_storage" {}
variable "rds_storage_encrypted" {}
# kms_key_id        = "arm:aws:kms:<region>:<account id>:key/<kms key id>"
variable "rds_db_name" {}
variable "rds_username" {}
variable "rds_password" {}
variable "rds_port" {}
variable "rds_maintenance_window" {}
variable "rds_backup_window" {}
variable "rds_multi_az" {}
variable "rds_backup_retention_period" {}
variable "rds_enabled_cloudwatch_logs_exports" {}
variable "rds_param_family" {}
variable "rds_option_major_engine_version" {}
variable "rds_skip_final_snapshot" {}
variable "rds_deletion_protection" {}
variable "rds_parameters" {}
variable "rds_options" {}
variable "rds_monitoring_interval" {}
variable "rds_create_monitoring_role" {}
variable "rds_monitoring_role_name" {}
variable "rds_performance_insights_enabled" {}
variable "rds_performance_insights_retention_period" {}
